### ISSUE TITLE
ostree-go depends on unlicensed code

### ISSUE THREAD

**Issue by zumbi** [ostreedev/ostree-go#13]
Hello,

  I was wanting to package ostree-go for Debian OS software distribution, however it depends on github.com/14rcole/gopopulate, which turns out to be unlicensed code. I opened an issue in their upstream bugtracker (https://github.com/14rcole/gopopulate/issues/2) 15 days ago and I have not yet gotten any reply from them. Could you consider to move away from gopopulate or find licensed alternative until licensing issue is resolved?

Regards

**Comment by zumbi** [comment]
ping!

**Comment by 14rcole** [comment]
Hi @zumbi, sorry for the delayed response, it's been a crazy semester.  I actually created the gopopulate library for the purpose of testing ostree-go.  I'd be happy to add a license to it!

**Comment by zumbi** [comment]
@14rcole thanks very much, I'll close this issue as you have solved it in gopopulate!
Best regards
