### ISSUE TITLE
Commit gets stuck in staging directory

### ISSUE THREAD

**Issue by 14rcole** [ostreedev/ostree-go#4]
The Commit() function in the ostree-commit-refactor branch reports a successful commit, but the commit is left in a staging directory and never actually commited to the repo

**Comment by 14rcole** [comment]
It would appear that commits are written to the filesystem with write_object(), which is called by ostree_repo_write_metadata(), which is called by ostree_repo_write_commit_with_time(), which is either called by ostree-go or called by ostree_repo_write_commit() (which is called by ostree-go)

**Comment by 14rcole** [comment]
@cgwalters I've been working on this for the past couple of days without making any progress.  Have you encountered an issue like this when writing the CLI for ostree?  I would imagine that something is wrong with either the OstreeRepoFile or the metadata GVariant that I'm passing to ostree_repo_write_commit() but seeing as I can't see the values of the C structs when I'm writing them to Go, I can't tell which

**Comment by giuseppe** [comment]
@14rcole can you try if this works for you?

https://github.com/ostreedev/ostree/pull/689

**Comment by giuseppe** [comment]
@14rcole ported to ostree-go:

https://github.com/ostreedev/ostree-go/pull/5

**Comment by giuseppe** [comment]
is it fixed on master now?

**Comment by 14rcole** [comment]
I don't know, I've been in the midst of exams.  I can most likely check this weekend.

**Comment by giuseppe** [comment]
Let's close it. I have not heard of anything like that anymore and we are using it in Skopeo for all this time
